### PR TITLE
Feature/new navigation layout

### LINKED ISSUE #577: As a researcher, I want to have clear navigation view in SD Connect that I can find the features available in the service
### Design:

https://www.figma.com/file/N0Y3N0nfyMS2wG3gjwZ201/SD-Connect-Prototype?node-id=517%3A2533

### User stories:
- [x] #596
- [x] #597
- [x] #611
- [x] #612
- [x] #613
- [x] #715 
- [ ] #706 
- [ ] #648 
- [x] #701 
- [x] #702 
- [x] #716

### Tasks:

- [x] Update top bar visuals (Logo, User information)
- [x] Add language selection

### PR DESCRIPTION
**Pull request by saulipurhonen**
### Description

Redesigned navigation with CSC Design System components.
Layout can be seen at: [SD Connect layout](https://www.figma.com/file/N0Y3N0nfyMS2wG3gjwZ201/SD-Connect-Prototype?node-id=517%3A2532)

Note: This branch is based on [feature/new-error-pages](https://github.com/CSCfi/swift-browser-ui/tree/feature/new-error-pages), since it has already introduced the CSC Design System

### Related issues

Closes #577, #596 and #597 

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Changes Made

- Splitted navigation into main and secondary navigation components
- Use already defined language switcher component
- User menu
- Main navigation item styling
- Project switcher with new component library
- Button for folder creation and upload
- Support link target to CSC docs
- Updated E2E tests
- Updated changelog
- Adjusted footer to stay at the bottom of the page in browser view (this also helps in Cypress tests so footer doesn't block any content)
- Use CSC-logo component from design system
- Target browser view with current active folder id when clicking logo
- Display loading indicator in dashboard view when data is loading. Helps with E2E testing.

### Testing

- [x] Integration Tests

### CODE REVIEW

**Review by hannyle — CHANGES_REQUESTED** [review]
Overall looks good to me. It's nice to see some improvement in the code and tests as well.

Just some minor things I have noticed: 
- In the design, the text _CSC-IT Center For Science LTD_ was removed 
- I think the color of the text (_SD Connect_ and _Select Project_) should be #595959 (csc-dark-grey) ?
- And the logo is broken in BrowserPage (not sure if it only happens to me)

Screenshot 2022-06-29 at 9 14 39

**Comment by saulipurhonen** [comment]
> * In the design, the text _CSC-IT Center For Science LTD_ was removed

This text is alt-attribute for image and displays when image is broken.

> * I think the color of the text (_SD Connect_ and _Select Project_) should be #595959 (csc-dark-grey) ?

I'm not sure if we're supposed to change CSC Design System default color values? Maybe @ainoc can give an opinion on this? Also, changing shadow DOM values in design system components is somewhat problematic in some occasions where developer isn't able to add custom CSS classes to child elements of the component.

> * And the logo is broken in BrowserPage (not sure if it only happens to me)

Same thing's happening on my end. There seems to be a symlink in `assets/logo.svg` but it's an empty .svg file (pointed to `config/images`). @sampsapenna, have you used logo before and if so, any idea why it's not working / can't be found anymore?

**Comment by saulipurhonen** [comment]
> * I think the color of the text (_SD Connect_ and _Select Project_) should be #595959 (csc-dark-grey) ?

I changed the color and sizing of app heading to match layout prototype. See previous answer for _Select Project_.

**Comment by hannyle** [comment]
> > * In the design, the text _CSC-IT Center For Science LTD_ was removed
> 
> This text is alt-attribute for image and displays when image is broken.
> 
> > * I think the color of the text (_SD Connect_ and _Select Project_) should be #595959 (csc-dark-grey) ?
> 
> I'm not sure if we're supposed to change CSC Design System default color values? Maybe @ainoc can give an opinion on this? Also, changing shadow DOM values in design system components is somewhat problematic in some occasions where developer isn't able to add custom CSS classes to child elements of the component.
> 
> > * And the logo is broken in BrowserPage (not sure if it only happens to me)
> 
> Same thing's happening on my end. There seems to be a symlink in `assets/logo.svg` but it's an empty .svg file (pointed to `config/images`). @sampsapenna, have you used logo before and if so, any idea why it's not working / can't be found anymore?

I agree, it's a challenge for me also to customise/modify the CSS classes of csc-components.
At least from the [website]( https://csc-design-system-docs.web.app/templates/basic-template), we could add the logo as `<c-csc-logo/>`.

**Review by hannyle — APPROVED** [review]

**Comment by saulipurhonen** [comment]
> * I think the color of the text (_SD Connect_ and _Select Project_) should be #595959 (csc-dark-grey) ?

As a note: I've inquired this from @ainoc. Let's open another PR If we decide to change default values of the component library since this isn't most straightforward thing to do and in this case it might be wise to have wrapper components to unify all custom color options.

**Pull request merged**
