### PR TITLE
Bugfix/small window modal behaviour

### PR DESCRIPTION
**Pull request by emm1R**
### Description

Create folder modal does not shrink needlessly for smaller windows.

### Related issues

Fixes Gitlab issue #929

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### Testing

- [x] Tests do not apply

### CODE REVIEW

**Comment by emm1R** [comment]
Again forgot to change master->devel, so there are dependency problems that do not go away.

**Comment by csc-felipe** [comment]
Funny that it has some formatting complaints

**Review by blankdots — APPROVED** [review]

**Comment by hannyle** [comment]
Besides the style check error, the fix looks good to me :)

**Comment by mradavi** [comment]
The modal definitely looks better when resized now!

**Review by blankdots — APPROVED** [review]

**Pull request merged**
