### PR TITLE
migrate away from buefy

### PR DESCRIPTION
**Pull request by csc-felipe**
### Description

All `buefy` components have been removed from `devel`, and this PR merely removes the `buefy` package and its references.

### Changes Made

- Remove `buefy` dependency

### CODE REVIEW

**Comment by csc-felipe** [comment]
rebased

**Comment by csc-felipe** [comment]
Split this PR into 2 more PRs #1015 and #1016.

**Comment by csc-felipe** [comment]
rebased

**Comment by csc-felipe** [comment]
rebased

**Comment by csc-felipe** [comment]
All buefy components have been removed from `devel`, so this PR is ready to be merged (after review, ofc)

**Review by hannyle — DISMISSED** [review]
The input field in TagInput has disappeared. I think it could be fixed by adding `scoped` to `<style>` so it doesn't affect other inputs.

https://github.com/CSCfi/swift-browser-ui/blob/feature/dump-buefy/swift_browser_ui_frontend/src/components/CUploadButton.vue#L64-#L68

**Review by hannyle — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
