### PR TITLE
Allow adding commit hash and url to footer in dev mode

### PR DESCRIPTION
**Pull request by csc-felipe**
### Description

Add new fields to the footer that are only visible in dev mode. The values are extrated with `git` command when building in development mode, e.g. `npm run build-devel`.

image

The version string follows the [`git describe` command](https://git-scm.com/docs/git-describe#_examples).
So in `feature/footer-version | v2.0.0-607-gcaf95d5d`

- `feature/footer-version` is the branch name
- `v2.0.0` indicates the git tag for the release version;
- `607` is the number of commits since the tagged commit;
- `gcaf95d5d` is the shortened commit hash (after removing `g`, so `caf95d5d`)

You can see the commit with `git show caf95d5d`

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Changes Made

- Add a git branch, version and link to the footer, which is only visible in dev mode

### Testing

- [x] Tests do not apply

### CODE REVIEW

**Review by blankdots — COMMENTED** [review]
i am not sure I am following why we cannot add a command on build or a env var on build to get the latest commit e.g.
```
"build-devel": "APP_VERSION=$(git rev-parse HEAD) && vue-cli-service build --mode development", 
```

or
in vue.config.json
```
process.env.VUE_APP_GIT_HASH = require('child_process').execSync('git rev-parse --short HEAD')
````

or use an npm package.


... and include it directly instead of making it like this and processing the commit in the docker images (which i think we might need to change as part of this PR, if we keep these changes) ?

**Comment by csc-felipe** [comment]
I tried to make it without using `git` command ^^. 

I think the approach you mentioned would not be able to use caching for UI assets in Docker, or in other words, docker might use a cache of a previous commit with the current images. I do think overriding the language files is a good compromise considering how we deploy.

**Review by blankdots — CHANGES_REQUESTED** [review]
modify docker-dev files to make use of this commit

**Comment by csc-felipe** [comment]
The feature is only for deployment, the Dockerfiles in this repo will not be changed.

Or why would you want them to be changed?

**Comment by blankdots** [comment]
> The feature is only for deployment, the Dockerfiles in this repo will not be changed.
> 
> Or why would you want them to be changed?

to me it makes sense to change them as well, if we have dev dockerfiles and we provide them in this repository

**Comment by csc-felipe** [comment]
Yes, but somehow I feel like that would be a different feature. The current feature's intention is to provide the git hash on our deployment environment. Not during development.

**Comment by blankdots** [comment]
> Yes, but somehow I feel like that would be a different feature. The current feature's intention is to provide the git hash on our deployment environment. Not during development.

personally i would find it useful during development as well, as I know which changes are being used, just to spot caching issue. 
That being said, I am fine with not adding it as well.

**Review by blankdots — APPROVED** [review]

**Comment by csc-felipe** [comment]
Ok, I'll try your suggestion for making it work both in Docker and local dev.

**Comment by csc-felipe** [comment]
The problem now is that it will always show dirty, as usually the build process modify something. It would be useful, though, to have it there during development.

image

**Comment by blankdots** [comment]
> The problem now is that it will always show dirty, as usually the build process modify something. It would be useful, though, to have it there during development.
> 
> image

that is fine, if that is really troublesome we can remove the string. it is fine as is.

**Comment by csc-felipe** [comment]
Removed the `dirty` flag

**Review by blankdots — APPROVED** [review]

**Pull request merged**
