### PR TITLE
properly clean dropitemlist

### LINKED ISSUE #465: Drag-n-drop file listing state is not synced to upload view
#### Describe the bug

Dropped files repopulate into the upload view file listing after deletion, if new files are added via drag-n-drop.

#### To Reproduce
Steps to reproduce the behaviour:
1. select upload
2. drag-and-drop a file to the page
3. remove it from the list. List will be empty
4. drag-and-drop another file to the page
5. both files are on the list, also the previously removed one
If the second file is the same as the first one, it is twice on the list.

#### Expected behavior

File removals from the UI are synced to the vuex and do not repopulate into the index.

#### Additional context

This is a Firefox only bug.

### LINKED ISSUE #499: Clear items to upload on the upload UI
#### Proposed solution
The only way to remove items from the upload list, is to click one by one on the remove button. Closing the upload page by navigating away does not clear the items, which is ok (perhaps even a feature), but there should be some way to clear the list more easily.

#### DoD (Definition of Done)
- Add a clear or cancel button that removes items from upload list. A clear button would only clear the list, while a cancel button would clear the list and "close" the upload view.

### LINKED ISSUE #500: Upload UI: Selecting files button works only once
#### Describe the bug
Selecting files with the button works only the first time. A person cannot select files from different locations for the upload.

#### To Reproduce
Steps to reproduce the behaviour:
1. Go to upload page
2. Click on "Select files to upload"
3. Select some files, and click OK
4. Click on "Select files to upload"
5. Select some files, and click OK
6. Notice that new files were not added

#### Expected behavior
Selecting files should always add them.

### PR DESCRIPTION
**Pull request by blankdots**
### Description

I think i introduced this with #497 

### Related issues

Closes #465 
Closes #500
Closes #499

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### Changes Made

1. erase store with drag and drop list
2. move drag and drop files as well as files uploaded by button to store
3. more styles to dropbox area
4. fix uploading from multiple directories by using the select files button
5. added cancel and clear files buttons

Peek 2022-02-09 17-21

### Testing

- [x] Tests do not apply

### CODE REVIEW

**Comment by csc-felipe** [comment]
Made a couple of follow-up issues: #499 #500.

**Comment by blankdots** [comment]
@csc-felipe fixed #500 
Peek 2022-02-10 11-33

**Comment by blankdots** [comment]
@csc-felipe fixed #499 as well
Peek 2022-02-10 13-15

**Comment by csc-felipe** [comment]
Super!

**Pull request merged**
