### PR TITLE
Update/bulk update front nov2021

### PR DESCRIPTION
**Pull request by blankdots**
### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Changes Made

1. update npm dependencies
2. bump npm in github actions
3. solve `Component name x should always be multi-word`

### Testing

- [x] Tests do not apply

### CODE REVIEW

**Review by csc-felipe — COMMENTED** [review]
Overall looks good, and nice to have explicitly in the name whether it's a component, a view, or a page. I'm not so familiar with Vuejs and the frontend codebase yet, so my comments may be off. 

- Why isn't `pages/LoginPassword.vue` changed to `pages/LoginPasswordPage.vue`?

- Why aren't all the components under `views/` named `ComponentView`?

- Other files could be renamed to follow the pattern, what do you think? e.g.: `components/ReplicateContainer.vue`-> `components/ReplicateContainerButton.vue`

**Comment by blankdots** [comment]
@csc-felipe with the PR tried to update just the minimum to make the dependecies updated. 
I suggest we have another PR if we want to refactor the names, not to extend this PR far from its intended purpose.

**Comment by csc-felipe** [comment]
Makes sense. I only saw your comment in the chat about vue-cli lint changes afterwards. I didn't realize from the description that `Component name x should always be multi-word` was from the updated linting requirements.

**Review by csc-felipe — APPROVED** [review]
Looks good.

**Review by sampsapenna — APPROVED** [review]
lgtm 👍🏼

**Pull request merged**
