### PR TITLE
Tab based view for folders

### LINKED ISSUE #638: Tabs
Given that wants to see all folders in selected project
when user selects All folders tab
then user sees all folders in selected project.

Given that wants to see folders that he has shared with other projects
when user selects Folders you have shared tab
then user sees only folders that user has shared.

Given that wants to see folders that are shared with him from other projects
when user selects Folders shared with you tab
then user sees only folders that are shared with user.

### PR DESCRIPTION
**Pull request by saulipurhonen**
### Description

This PR introduces tab based view for folder components.

### Related issues

Closes #638 

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Changes Made

- Added parent component for dynamic folder component rendering
- Appended routes to match views for shared folders
- Created tab component for folder tabs
- Renamed `ContainersView` route to `AllFolders`
- Renamed routes for already existing sharing views so these don't interfere with new feature
- Added translations for new strings
- Removed css class names and handle block spacing in parent container in folders view
- Added simple integration Cypress test for tab change
- Updated changelog
- Appended Finnish word list

### Testing

- [x] Integration Tests

### CODE REVIEW

**Review by hannyle — APPROVED** [review]
LGTM!

**Review by sampsapenna — CHANGES_REQUESTED** [review]
Localisation is not working for the tab labels, as they're not using `vue-i18n`. This needs to be taken care of before merging. Other than that LGTM.

**Comment by sampsapenna** [comment]
> Localisation is not working for the tab labels, as they're not using `vue-i18n`. This needs to be taken care of before merging. Other than that LGTM.

Rephrasing, it's using `i18n` but reactivity is broken due to how CSC components work compared to actual vue ones. I'll push a fix for this shortly to get the PR merged 👍🏼

**Comment by sampsapenna** [comment]
Pushed a fix for `i18n`, incorrect language dict keys (they were the wrong way round, to was from and vice versa) and made `activeTab` reactive by making it a computed variable instead of a function.

**Review by sampsapenna — APPROVED** [review]

**Comment by sampsapenna** [comment]
Rebased to fix the merge conflicts 👍🏼 Merging when tests are done.

**Comment by hannyle** [comment]
LGTM!

**Pull request merged**
