### PR TITLE
Replaced buefy toasts with CSC toasts

### PR DESCRIPTION
**Pull request by mradavi**
### Description

Replaced buefy toasts with c-toasts. Consulted with the UX lead on this: duration is 6s (which is the default). 

### Related issues
GL 944.

I just removed the toasts that are in to-be-deleted files (see PR #1006). Please check if everything looks alright.

### CODE REVIEW

**Comment by mradavi** [comment]
Changed to WIP. Looks like toasts should be around / below the user action, I'll change to that.

**Comment by csc-felipe** [comment]
> Looks like toasts should be around / below the user action, I'll change to that.

Maybe that could come in another PR?

**Comment by mradavi** [comment]
> > Looks like toasts should be around / below the user action, I'll change to that.
> 
> Could that come in another PR?

Yes, it would be good to review all the toasts. I haven't changed the existing c-toasts.

**Review by csc-felipe — DISMISSED** [review]

**Review by blankdots — COMMENTED** [review]
changelog would be nice

**Comment by mradavi** [comment]
> changelog would be nice

Updated!

**Review by blankdots — APPROVED** [review]

**Pull request merged**
